"""
Semi-automated job submitter using Playwright.

Design principle: Human-in-the-loop.
- The script fills what it can from resume data.
- It PAUSES and shows the user the pre-filled form before submitting.
- The user presses Enter to confirm or S to skip.
- For PhD applications, a motivation letter is generated by DeepSeek API.
"""
import json
import os
from pathlib import Path

from openai import OpenAI
from playwright.sync_api import sync_playwright, Page

from src.db import get_matched, update_status
from src.parser import load_resume, DEEPSEEK_BASE_URL
from src.scrapers.boss import COOKIES_FILE as BOSS_COOKIES

ML_SYSTEM = """You are an academic writing assistant. Write a concise motivation letter
for a PhD application. Use formal academic English. Max {max_words} words.
Format: plain text, no headers, no bullet points.
Be specific about why this particular research group and how the applicant's background fits."""


def _generate_motivation_letter(
    resume: dict,
    job: dict,
    api_key: str,
    model: str,
    max_words: int = 400,
) -> str:
    client = OpenAI(api_key=api_key, base_url=DEEPSEEK_BASE_URL)
    prompt = (
        f"Resume summary:\n{json.dumps(resume, ensure_ascii=False)}\n\n"
        f"PhD project:\nTitle: {job['title']}\nInstitution: {job['company']}\n"
        f"Description: {job['description'][:2000]}"
    )
    response = client.chat.completions.create(
        model=model,
        max_tokens=2048,
        messages=[
            {"role": "system", "content": ML_SYSTEM.format(max_words=max_words)},
            {"role": "user", "content": prompt},
        ],
        reasoning_effort="high",
        extra_body={"thinking": {"type": "enabled"}},
    )
    return response.choices[0].message.content.strip()


def _confirm(prompt_text: str) -> bool:
    ans = input(f"\n{prompt_text} [Enter=确认 / s=跳过]: ").strip().lower()
    return ans != "s"


def _handle_no_url_job(job_id: int, title: str, company: str, description: str, summary: str, dry_run: bool = False) -> None:
    """Human-assisted flow for jobs that have no direct URL (Liepin fallback entries)."""
    import urllib.parse

    print("\n⚠  无直接链接，请手动搜索投递。职位信息：")
    if description:
        print(f"  详情: {description[:300]}")

    kw = urllib.parse.quote(f"{title} {company}".strip())
    print("\n  搜索建议：")
    print(f"  Boss直聘:  https://www.zhipin.com/web/geek/job?query={kw}")
    print(f"  猎聘:      https://www.liepin.com/zhaopin/?key={urllib.parse.quote(title)}")

    if dry_run:
        ans = input("\n[测试模式] 按 Enter 继续 / q=结束: ").strip().lower()
        if ans == "q":
            raise KeyboardInterrupt
        print("→ [测试模式] 不写入数据库")
        return

    ans = input("\n投递完成后标记状态 [Enter=已投递 / s=跳过 / q=结束本次流程]: ").strip().lower()
    if ans == "q":
        raise KeyboardInterrupt
    elif ans == "s":
        update_status(job_id, "skipped")
        print("→ 已标记为跳过")
    else:
        update_status(job_id, "submitted")
        print("→ 已标记为已投递")


def _fill_common_fields(page: Page, resume: dict) -> None:
    """Try to fill name/email/phone fields if they exist on the page."""
    field_map = {
        "name":  resume.get("name", ""),
        "email": resume.get("email", ""),
        "phone": resume.get("phone", ""),
    }
    for field, value in field_map.items():
        if not value:
            continue
        for selector in [
            f'input[name*="{field}"]',
            f'input[placeholder*="{field}"]',
            f'input[id*="{field}"]',
        ]:
            els = page.query_selector_all(selector)
            for el in els:
                try:
                    el.fill(value)
                except Exception:
                    pass


def submit_jobs(
    min_score: int = 70,
    api_key: str = "",
    model: str = "deepseek-v4-flash",
    max_words: int = 400,
    dry_run: bool = False,
) -> None:
    resume  = load_resume()
    jobs    = get_matched(min_score=min_score)
    key     = api_key or os.environ.get("DEEPSEEK_API_KEY", "")

    if not jobs:
        print(f"没有匹配分数 ≥ {min_score} 的职位。请先运行: python main.py match")
        return

    print(f"\n找到 {len(jobs)} 个匹配职位 (分数 ≥ {min_score})\n")

    boss_cookies = []
    if BOSS_COOKIES.exists():
        boss_cookies = json.loads(BOSS_COOKIES.read_text(encoding="utf-8"))

    with sync_playwright() as pw:
        browser = pw.chromium.launch(headless=False)

        try:
            for job in jobs:
                job_id   = job["id"]
                platform = job["platform"]
                title    = job["title"]
                company  = job["company"]
                url      = job["url"]
                score    = job["match_score"]

                summary = ""
                if job["match_data"]:
                    try:
                        summary = json.loads(job["match_data"]).get("summary", "")
                    except Exception:
                        pass

                print("─" * 60)
                print(f"[{platform.upper()}] {title} @ {company}")
                print(f"分数: {score}  URL: {url}")
                if summary:
                    print(f"AI 评价: {summary}")

                if url.startswith("mcpjobs://"):
                    _handle_no_url_job(job_id, title, company, job["description"] or "", summary, dry_run=dry_run)
                    continue

                if not _confirm("是否处理这条职位？"):
                    if not dry_run:
                        update_status(job_id, "skipped")
                    print("→ 已跳过" + (" [测试模式]" if dry_run else ""))
                    continue

                ctx  = browser.new_context()
                page = ctx.new_page()

                if platform == "boss" and boss_cookies:
                    ctx.add_cookies(boss_cookies)

                page.goto(url, timeout=30_000)
                page.wait_for_load_state("networkidle", timeout=15_000)

                _fill_common_fields(page, resume)

                # For PhD platforms: generate and paste motivation letter
                if platform in ("findaphd", "phdportals") and key:
                    print("\n正在生成动机信（Motivation Letter）...")
                    letter = _generate_motivation_letter(resume, dict(job), key, model, max_words)
                    print("\n" + "─" * 40)
                    print("生成的动机信草稿：\n")
                    print(letter)
                    print("─" * 40)
                    for sel in ["textarea", 'div[contenteditable="true"]']:
                        areas = page.query_selector_all(sel)
                        for area in areas:
                            try:
                                area.fill(letter)
                                break
                            except Exception:
                                pass

                print("\n浏览器已打开职位页面并完成预填充。请检查内容后手动提交。")
                if dry_run:
                    if input("[测试模式] 按 Enter 继续 / q=结束: ").strip().lower() == "q":
                        raise KeyboardInterrupt
                    print("→ [测试模式] 不写入数据库")
                elif not _confirm("提交完成后，确认标记为已投递？"):
                    update_status(job_id, "skipped")
                    print("→ 已标记为跳过")
                else:
                    update_status(job_id, "submitted")
                    print("→ 已标记为已投递")

                ctx.close()

        except KeyboardInterrupt:
            print("\n→ 用户终止，退出投递流程。")

        browser.close()
    print("\n投递流程完成。")
